### PR TITLE
mod: bump aws Go sdk to v1.47.11 to support EKS pod identities

### PR DESCRIPTION
**Pull request by scbizu**
References:

- [Chartmuseum #764](https://github.com/helm/chartmuseum/issues/764)
- [AWS doc](https://docs.aws.amazon.com/eks/latest/userguide/pod-id-minimum-sdk.html)

### CODE REVIEW

**Comment by scbizu** [comment]
@cbuto PTAL

**Review by cbuto — APPROVED** [review]
thanks @scbizu!

**Comment by wesleyorama2** [comment]
Hey @scbizu, just to make sure this doesn't get dropped when should it be merged?

**Comment by wesleyorama2** [comment]
lol, thanks I appreciate that.

**Comment by scbizu** [comment]
Sorry, I am sick these days . I will bump the museum soon.

**Comment by wesleyorama2** [comment]
> Sorry, I am sick these days . I will bump the museum soon.

I am sorry to hear that. I hope you get better. Please do not push yourself, I can just use a S3 bucket by itself until this gets built.

**Pull request merged**
