### PR TITLE
Support for Baidu Cloud BOS storage backend

### PR DESCRIPTION
**Pull request by clarklee92**
Signed-off-by: Li Hao clarklee1992@hotmail.com

I have used chartmuseum with [Baidu Object Storage](https://cloud.baidu.com/product/bos.html) backend successfully and Implemented the interface. I will push the left code to chartmuseum ASAP if this pr accepted.
Many thanks, sincerely yours
clark

### CODE REVIEW

**Comment by jdolitsky** [comment]
Awesome thanks! will sign up for Baidu and take a look asap

**Comment by clarklee92** [comment]
Sorry about that. I only tested `baidu_test.go` for the first time and there is a redeclare with `alibaba_test.go`. Now fixed and `make test` passed. Again please and thanks a lot.

**Comment by jdolitsky** [comment]
Thanks again @clarklee92 ! This is now available in new release v0.3.0

**Comment by jdolitsky** [comment]
Opened https://github.com/helm/chartmuseum/issues/197 to track support in chartmuseum server

**Pull request merged**
