### PR TITLE
chore: add constructor for amazon with credentials

### PR DESCRIPTION
**Pull request by koalado**
Have added another constructor for the amazon s3 backend because of an error message due to missing credentials.

Related issue: https://github.com/chartmuseum/storage/issues/23

### CODE REVIEW

**Comment by jdolitsky** [comment]
@koalado can you please resubmit, without removing go.mod/go.sum file? Thank you

**Comment by koalado** [comment]
> @koalado can you please resubmit, without removing go.mod/go.sum file? Thank you

yeah sure, will do it later this week when I'm back at it

**Comment by koalado** [comment]
@jdolitsky couldn't wait. It's done 😉

**Comment by jdolitsky** [comment]
@koalado thanks! lgtm

**Pull request merged**
