### PR TITLE
feature: support for Tencent Cloud COS storage backend

### PR DESCRIPTION
**Pull request by scaat**
I have used chartmuseum with [Tencent Object Storage](https://cloud.tencent.com/product/cos) backend successfully and Implemented the interface.

### CODE REVIEW

**Comment by scaat** [comment]
@jdolitsky

**Comment by jdolitsky** [comment]
@scaat sorry for long delay. I did not not get these notifications for some reason. Will check this out shortly, thanks!

**Comment by jdolitsky** [comment]
@scaat merged thanks again!

**Comment by scaat** [comment]
@jdolitsky This is my honor, thank you. When will the next release ? I will push the left code to chartmuseum ASAP.

**Pull request merged**
